package design

import (
	_ "goa-study/design/resources/beers"

	. "goa-study/env"

	. "github.com/goadesign/goa/design"
	. "github.com/goadesign/goa/design/apidsl"
)

var _ = API("BeerBoxAPI", func() {
	Title("goa勉強用API")
	Description("goa勉強用API")
	Host(Server.APIHostStringOnDoc())
	Scheme("http")
	BasePath("/api")
	Consumes("application/json") // Media types supported by the API
	Produces("application/json") // Media types generated by the API
})
